### ISSUE TITLE
Make the export an object instead of an array

### ISSUE THREAD

**Issue by getkey** [joelgallant/rollup-plugin-dir-import#1]
Hey Joel, this looks like a nice plugin!

I would like to request a change if it sounds sane to you: making the export an object instead of an array.
The value would be the default export, as it is now. The key would be the filename (perhaps with the extension trimmed?).

My use-case is a folder where I store a bunch of JSON game maps. I need the maps themselves, but also their name so I can refer to them easily.

The user would be still able to get an array if they wish by calling `Object.values(module)`.

**Comment by joelgallant** [comment]
For my use case, an array makes most sense as default export. I could add a named `files` export with `[filename-w/o-ext]: export` though fairly easily. Let me take a stab at that.

**Comment by getkey** [comment]
Thank you very much! :raised_hands:
